name: Pipeline API .NET

on:
  push:
    branches:
      - master


  pull_request:
    branches:
      - master


jobs:
  build-e-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build da aplicação
        run: dotnet build --no-restore

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal